steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/stinky-pinky-brain-dev:$COMMIT_SHA', '.']
  id: 'Build Docker Image'

- name: 'gcr.io/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/stinky-pinky-brain-dev:$COMMIT_SHA'
  entrypoint: 'bash' 
  args: ['-c', 'python -m unittest discover tests']
  id: 'Run Unit Tests'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - run
  - deploy
  - stinky-pinky-brain-dev
  - '--image'
  - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/stinky-pinky-brain-dev:$COMMIT_SHA'
  - '--region'
  - northamerica-northeast1
  - '--platform'
  - managed
  - '--allow-unauthenticated'
  id: 'Deploy to Cloud Run'
  waitFor: ['Run Unit Tests']  # Only deploy if tests pass

images:
  - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/stinky-pinky-brain-dev:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY