steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:$COMMIT_SHA', '.']
  id: "Build"

- name: 'gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:$COMMIT_SHA'
  entrypoint: 'bash' 
  args: ['-c', 'python -m unittest discover tests']
  id: "Test"

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - run
  - deploy
  - stinky-pinky-brain-dev
  - '--image'
  - gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:$COMMIT_SHA
  - '--region'
  - northamerica-northeast1
  - '--platform'
  - managed
  - '--allow-unauthenticated'
  id: "Deploy"

images:
  - gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:$COMMIT_SHA

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY