# This file defines the build, test, and deploy steps for your Cloud Run service

steps:
- name: 'gcr.io/cloud-builders/docker'  # Use the Docker build image
  args: ['build', '-t', 'gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:latest', '.']  # Build the Docker image

- name: 'gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:latest'  # Use the built image to run tests
  entrypoint: 'bash' 
  args: ['-c', 'python -m unittest discover tests']  # Execute unit tests

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use the Cloud SDK image
  args: 
  - gcloud
  - run
  - deploy
  - stinky-pinky-brain-dev  # Name of your Cloud Run service
  - '--image'
  - gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:latest
  - '--region'
  - northamerica-northeast1        # Adjust the region as needed
  - '--platform'
  - managed
  - '--allow-unauthenticated'

images:
  - gcr.io/stinky-pinky-app/stinky-pinky-brain-dev:latest

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY