openapi: 3.0.0
info:
  title: Stinky Pinky AI API
  description: An API that generates word puzzles using Generative AI.
  version: 1.0.0
servers:
  - url: /
paths:
  /:
    get:
      description: Serves this page - the Swagger Docs.
      responses:
        200:
          description: HTML content for the API Docs.

  /api/generate:
    get:
      description: Generates a word puzzle using AI. Requires a valid API key.
      responses:
        200:
          description: A JSON object containing the generated word puzzle.
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: object
                    properties:
                      clue1: 
                        type: string
                      clue2:
                        type: string
                      word1:
                        type: string
                      word2:
                        type: string
        400:
          description: Bad request. Missing or invalid API key.
        500:
          description: Internal server error. Problem with training data or prompt.
        404:
          description: Not found. Error occurred during puzzle generation.

  /{path}: 
    get:
      description: Serves static files (CSS, JavaScript, images) for the web interface.
      parameters:
        - in: path
          name: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: The requested static file.

components:
  securitySchemes:
    ApiKeyAuth:        # TODO
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
